# coding: utf-8
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'CacheTracker/CoreData', :path => './..'
  pod 'CacheTracker/Realm', :path => './..'
  pod 'CacheTracker/Array', :path => './..'
  pod 'MagicalRecord'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
